In [1]:
import torch

In [2]:
def activation(x):
    return 1/(1+torch.exp(-x))

In [8]:
#Generate some data
torch.manual_seed(7)

# Features are 5 random normal variables
features = torch.randn((1,5))
# True weights for our data, random normal variables(1,5) again
weights = torch.randn_like(features)
#Bias
bias = torch.randn((1,1))

#torch.sum(features*weights)+bias


tensor([[-1.6619]])

In [7]:
y_1 = activation(torch.sum(features * weights)+ bias)
print(y_1)
y_2 = activation((features * weights).sum() + bias)
print(y_2)

tensor([[0.1595]])
tensor([[0.1595]])


In [9]:
torch.mm(features,weights)

RuntimeError: size mismatch, m1: [1 x 5], m2: [1 x 5] at ..\aten\src\TH/generic/THTensorMath.cpp:961

In [10]:
activation(torch.mm(features,weights.view(5,1))+bias)

tensor([[0.1595]])

In [11]:
a = weights.reshape(5,1)

In [12]:
activation(torch.mm(features,a)+bias)

tensor([[0.1595]])

In [13]:
#Generate some data
torch.manual_seed(7)

#Features are 3 random normal variables
features = torch.randn((1,3))

#Define the size of each layer in our network
n_input = features.shape[1]
n_hidden = 2
n_output =1

#weights for inputs to hidden layers
W1 = torch.randn(n_input,n_hidden)
W2 = torch.randn(n_hidden,n_output)

#Bias
B1 = torch.randn((1,n_hidden))
B2 = torch.randn((1,n_output))

#Calculate the output for this multi-layer network using the weights W1&W2, and the biases, B1&B2.

In [17]:
activation(torch.mm(activation(torch.mm(features,W1)+B1),W2)+B2)

tensor([[0.3171]])

In [18]:
#OR
h = activation(torch.mm(features,W1)+B1)
output = activation(torch.mm(h,W2)+B2)
print(output)

tensor([[0.3171]])


In [19]:
#Torch to Numpy and Numpy to Torch
import numpy as np
a = np.random.rand(4,3)
a

array([[0.67641406, 0.1657233 , 0.49680738],
       [0.91598689, 0.74150113, 0.5536403 ],
       [0.84179555, 0.88221786, 0.53002486],
       [0.7137096 , 0.78940229, 0.79468334]])

In [20]:
b = torch.from_numpy(a)
b

tensor([[0.6764, 0.1657, 0.4968],
        [0.9160, 0.7415, 0.5536],
        [0.8418, 0.8822, 0.5300],
        [0.7137, 0.7894, 0.7947]], dtype=torch.float64)

In [22]:
b.numpy()

array([[0.67641406, 0.1657233 , 0.49680738],
       [0.91598689, 0.74150113, 0.5536403 ],
       [0.84179555, 0.88221786, 0.53002486],
       [0.7137096 , 0.78940229, 0.79468334]])

In [23]:
#Multiply Pytorch Tensor by 2, in place
b.mul_(2)

tensor([[1.3528, 0.3314, 0.9936],
        [1.8320, 1.4830, 1.1073],
        [1.6836, 1.7644, 1.0600],
        [1.4274, 1.5788, 1.5894]], dtype=torch.float64)

In [24]:
#a also change
a

array([[1.35282812, 0.33144659, 0.99361476],
       [1.83197378, 1.48300226, 1.1072806 ],
       [1.6835911 , 1.76443572, 1.06004972],
       [1.42741921, 1.57880457, 1.58936668]])